FROM node:18-alpine AS node
FROM webdevops/php-dev:8.0-alpine

COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

RUN echo 'display_errors = 1' > /opt/docker/etc/php/php.ini
WORKDIR /app
EXPOSE 8001 8000
COPY . .
COPY --chown=application:application . .
CMD bash -c "npm install && composer install && app/ice dbup && npm run dev"
