#!/usr/bin/env  php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}
require 'scoop/Context.php';
\Scoop\Context::load('app/config');
array_shift($argv);
$commandName = array_shift($argv);
$trace = $commandName === '--trace';
$environment = \Scoop\Context::getEnvironment();
if ($trace) {
    $commandName = array_shift($argv);
}
if (preg_match('/^[a-z][\w-]*$/', $commandName)) {
    $commandBus = new \Scoop\Command\Bus($environment->getConfig('commands', array()) + array(
        'new' => '\Scoop\Command\Creator',
        'dbup' => '\Scoop\Command\Structure'
    ));
    try {
        $commandBus->dispatch($commandName, $argv);
    } catch (Exception $ex) {
        $code = intval($ex->getCode());
        \Scoop\Command::writeLine(
            $ex->getMessage() . ($trace ? PHP_EOL . $ex->getTraceAsString() : ''),
            \Scoop\Command\Color::RED
        );
        exit($code ? $code : 1);
    }
} else {
    echo 'ICE/SCOOP version ',
    \Scoop\Command::writeLine(
        $environment->getVersion(), \Scoop\Command\Color::YELLOW, \Scoop\Command\Format::BOLD
    );
    echo PHP_EOL, 'Commands:', PHP_EOL;
    foreach ($commands as $command => $controller) {
        echo $command, ' => ', \Scoop\Command::writeLine($controller . '.php', \Scoop\Command\Color::BLUE);
    }
    echo PHP_EOL, 'Options:', PHP_EOL, '--trace => show exception stack when execute a command', PHP_EOL,
    PHP_EOL, 'Run app/ice COMMAND --help for more information', PHP_EOL;
}
