#!/usr/bin/env  php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}
require 'scoop/Context.php';
\Scoop\Context::load('app/config');
array_shift($argv);
$commandName = array_shift($argv);
$trace = $commandName === '--trace';
$environment = \Scoop\Context::getEnvironment();
if ($trace) {
    $commandName = array_shift($argv);
}
$writer = new \Scoop\Command\Writer();
$commands = $environment->getConfig('commands', array()) + array(
    'new' => 'Scoop\Command\Handler\Creator',
    'dbup' => 'Scoop\Command\Handler\Structure'
);
if ($commandName !== null && preg_match('/^[a-z][\w-]*$/', $commandName)) {
    $commandBus = new \Scoop\Command\Bus($commands);
    try {
        $commandBus->dispatch($commandName, $argv);
    } catch (Exception $ex) {
        $code = intval($ex->getCode());
        $writer->writeError(
            $ex->getMessage() . ($trace ? PHP_EOL . $ex->getTraceAsString() : ''),
            \Scoop\Command\Style\Color::RED
        );
        exit($code ? $code : 1);
    }
} else {
    $writer->write(
        array('ICE/SCOOP version '),
        array($environment->getVersion(), \Scoop\Command\Style\Color::YELLOW, \Scoop\Command\Style\Format::BOLD),
        array(PHP_EOL . PHP_EOL . 'Commands:')
    );
    foreach ($commands as $command => $controller) {
        $writer->write(
            array("$command => "),
            array($controller . '.php', \Scoop\Command\Style\Color::BLUE)
        );
    }
    $writer->write(
        array(PHP_EOL . 'Options:'),
        array(PHP_EOL . '--trace => show exception stack when execute a command'),
        array(PHP_EOL . 'Run app/ice COMMAND --help for more information')
    );
}
