version: '3.9'
services:
  webapp:
    container_name: webapp
    build:
      dockerfile: Dockerfile
    volumes:
      - ../.:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - "db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_DISPLAY_ERRORS: 1
      XDEBUG_MODE: develop,coverage,debug,profile
      #XDEBUG_SESSION_START=scoop
      XDEBUG_IDE_KEY: scoop
      XDEBUG_CLIENT_HOST: host.docker.internal
    tty: true

  db:
    container_name: db
    image: postgres:14.1-alpine
    volumes:
      - ../../data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scoop
